name: Build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:


  build:

    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
        - os: windows-latest
          artifact: Windows
        - os: ubuntu-latest
          artifact: Linux
        - os: macos-latest
          artifact: MacOS

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: autoBuild
        
    - name: Install JUCE's Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: cd $GITHUB_WORKSPACE/imogen && bash install_linux_deps.sh

    - name: Run main build
      shell: bash
      run: cd $GITHUB_WORKSPACE/autoBuild && cmake -B Builds && cmake --build $GITHUB_WORKSPACE/autoBuild/Builds --config Release
