name: Basic repo maintenence & utils

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: "00 00 * * 1"

jobs:

  link-checker:

    name: Checking for dead links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1

  stale-pull-request-remover:

    name: Marking stale pull requests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'